name: Lazada Tracker

on:
  schedule:
    - cron: '0 */1 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

     - name: Install Packages
  run: |
    pip install pandas requests playwright

- name: Install Browser
  run: playwright install chromium

      - name: Run Tracker
        run: python tracker.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_ID }}
